### ISSUE TITLE
incompatible with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by mbraun81** [lansuite/lansuite#117]
Clean install via git clone (commit b51cbb9)
MySQL v5.7.20-0ubuntu0.16.04.1

Fehler: 
SQL-Failure. Database respondet: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column '<db>.ls_stats_auth.lasthit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Query: 
SELECT userid,lasthit FROM ls_stats_auth WHERE login = "1" AND (lasthit > 1515528332 OR lastajaxhit > 1515528872) AND userid > 0 GROUP BY userid

**Comment by andygrunwald** [comment]
Thanks. In MySQL 5.7 the engine is way more strict.
This might not be the only query that is failing.
This needs to be fixed.

@mbraun81 Is it an option for you to run MySQL 5.6 as a workaround until we fixed it?

**Comment by mbraun81** [comment]
Leider laufen auch noch andere Dinge auf dem Server, da will ich nun ungerne noch ne zwote Instanz von MySQL laufen lassen ;)

**Comment by M4LuZ** [comment]
Have a look at this: https://stackoverflow.com/questions/23921117/disable-only-full-group-by
Running `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));` once as privileged DB user should do the trick till the next MySQL restart.
But I have the sneaking suspicion that this will not be the last error caused by the version upgrades...

**Comment by mbraun81** [comment]
Can only be done by an user with SUPER permissions.
I'm not willing to set global vars for the mysql db.

**Comment by andygrunwald** [comment]
### How to reproduce

How to test this with `docker-compose`:

```yaml
version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/code
            - ./.docker/nginx-development.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: lansuite/lansuite:latest
        volumes:
            - .:/code
            - ./.docker/nginx-php-flags.conf:/usr/local/etc/php-fpm.d/php-flags.conf
        networks:
            - code-network
    mysql:
        image: mysql:5.6
        command: mysqld --sql-mode="only_full_group_by"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=lansuite
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
```

And just do a fresh installation.

### Root cause

Important piece from the [MySQL docs](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by):

> As of MySQL 5.7.5, the default SQL mode includes ONLY_FULL_GROUP_BY. (Before 5.7.5, MySQL does not detect functional dependency and ONLY_FULL_GROUP_BY is not enabled by default

That might be the reason why this issue didn't occur earlier.

### Fix

Applied in #126
